fix

diff --git a/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl b/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
@@ -53,8 +53,8 @@ install_brew_packages() {
 
     brew --version
 
-    if [ -f "${HOME}/.Brewfile" ]; then
-        brew bundle --global || echo "brew bundle failed."
+    if [ -f "${HOME}/Brewfile" ]; then
+        brew bundle --file="${HOME}/Brewfile" || echo "brew bundle failed."
     else
         echo "Brewfile not found, skipping brew bundle."
     fi
